<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByTitle($title,$city='', $category='')
    {
        $query =  $this->createQueryBuilder('event')
            ->leftJoin('event.city','ecity')
            ->leftJoin('event.category','ecategory')
            ->andWhere('event.title LIKE :title')
            ->setParameter('title','%'.$title.'%');

        if($city){
            $query->andWhere('ecity.title = :city')
                  ->setParameter('city',$city);
        }

        if($category) {
            $query->andWhere('ecategory.title = :category')
                  ->setParameter('category', $category);
        }

         return $query->orderBy('event.date','DESC')
            ->getQuery()
            ->execute();
    }
}
