<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByTitle($title,$city='', $category='')
    {
        return $this->createQueryBuilder('event')
            ->leftJoin('event.city','ecity')
            ->leftJoin('event.category','ecategory')
            ->andWhere('event.title LIKE :title')
            ->andWhere('ecity.title = :city')
            ->andWhere('ecategory.title = :category')
            ->setParameter('title','%'.$title.'%')
            ->setParameter('city',$city)
            ->setParameter('category',$category)
            ->orderBy('event.date','DESC')
            ->getQuery()
            ->execute();
    }
}
